version: '3'

services:
  # Database for Airflow
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always

  # Initialize Airflow
  airflow-init:
    image: apache/airflow:2.7.1
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - _AIRFLOW_DB_UPGRADE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
    command: version
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./crawler/scripts:/opt/crawler/scripts
      - ./data:/opt/crawler/data  # Tất cả dữ liệu bao gồm logs đều ở đây
      - ./.env:/opt/crawler/.env

  # Airflow Webserver
  airflow-webserver:
    image: apache/airflow:2.7.1
    depends_on:
      - postgres
      - airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - DOCKER_ENV=true  # Cho config.py biết đang chạy trong Docker
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs  # Airflow logs
      - ./crawler/scripts:/opt/crawler/scripts
      - ./data:/opt/crawler/data  # Tất cả dữ liệu crawler bao gồm logs
      - ./.env:/opt/crawler/.env
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always

  # Airflow Scheduler
  airflow-scheduler:
    image: apache/airflow:2.7.1
    depends_on:
      - postgres
      - airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - DOCKER_ENV=true  # Cho config.py biết đang chạy trong Docker
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs  # Airflow logs
      - ./crawler/scripts:/opt/crawler/scripts
      - ./data:/opt/crawler/data  # Tất cả dữ liệu crawler bao gồm logs
      - ./.env:/opt/crawler/.env
    command: scheduler
    restart: always

volumes:
  postgres-db-volume: